### ISSUE TITLE
'stack build' results in error S-8506

### ISSUE THREAD

**Issue by Emstar** [keithfancher/tvmv#1]
On both Windows and Linux, after installing `stack`, doing `stack build` results in an error. 

```
user@host:~$ stack build
Error: [S-8506]
Error parsing targets: The project contains no local packages (packages not marked with 'extra-dep')
```

I do see a `.local` directory but there's no `bin` directory inside of it and no sign of `tvmv`. 

I know nothing at all about `stack` and I am not sure if `tvmv` comes long for the ride with `stack`, like it's a repo and there's a new package directory... or if I have to point it to your YAML file? 

Anyway I think the documentation "Once you've got stack installed, it takes care of the rest" may be overly optimistic. :)

**Comment by keithfancher** [comment]
Thank you for reporting! I think the issue here is just some ambiguity in my documentation :D 

Those instructions are to build the project from source, so you'd first need to `git clone` the repository (or download the source from the "releases" page). Then, from _within_ that source directory (where the `package.yaml` file lives), you run `stack build`. Apologies for the misdirection! I'll try to clarify that in the README.

That said, you can skip all that and just download a binary release [from the releases page](https://github.com/keithfancher/tvmv/releases/tag/0.1.0) as well. Then you can just run it directly. (Either stick it in your path somewhere -- `/usr/local/bin/` is often a good choice if you're using Linux or MacOS -- or run it from wherever you like.)

I actually haven't had a chance to build (or test!) `tvmv` for Windows yet. In theory, it should work fine. In _theory_!

But to be honest, I'm out of the loop with Windows stuff, and am not even sure how amenable most Windows users are to command-line tools. But either way, I'll have to get out my Win10 laptop and give it a whirl!

**Comment by Emstar** [comment]
Thanks @keithfancher that makes much more sense! Not knowing _anything_ about `stack` I was hoping `tvmv` was part of its index of packages, and would magically appear. 

My server stuff is all unix-like, but I still rely on the Windows GUI for file ingestion and lots of mundane file handling... Like renaming. To really pay off in my workflow I would need a Windows binary, but now that I understand `stack` a little better I am sure I can produce one. I appreciate the help with the dumb questions.

If you can grow this into something similar to Filebot, with an initial search based off the filename, that would be stellar. Looking forward to seeing where this goes.

**Comment by keithfancher** [comment]
> Not knowing anything about stack I was hoping tvmv was part of its index of packages, and would magically appear.

That's a totally valid assumption! I actually haven't submitted `tvmv` to [hackage](https://hackage.haskell.org/) or [stackage](https://www.stackage.org/) yet, so the only way to get hold of it is to grab it from the releases page on Github or to build it. Otherwise, you'd have been on the right track.

> To really pay off in my workflow I would need a Windows binary

I dusted off my Win10 install today and built it. Worked great, mostly! Only minor issue I found in Windows was that Unicode characters in TV show names seemed to really confuse the terminal. I find that a little surprising, but... I'll look into it! Only affects very specific use-cases, though, luckily.

Oh, and I upped a windows binary [to the releases page](https://github.com/keithfancher/tvmv/releases/tag/0.1.0). Check it out if you like!

> I appreciate the help with the dumb questions.

Definitely not dumb questions... I've been mired in the Haskell universe for the past few months, so it's easy for me to forget the context that users might have (or lack). I definitely don't expect users to dig into the minutiae of the Haskell build system(s)!

> If you can grow this into something similar to Filebot, with an initial search based off the filename, that would be stellar. Looking forward to seeing where this goes.

Thanks for the kind words! I definitely hope to keep improving it, especially as I learn more about other people's workflows. That idea in particular -- trying to be smarter about what to search based on input filename alone -- has been [on my list](https://github.com/keithfancher/tvmv/blob/master/PLAN.md) since day one :smile: 

I'm going to close this issue for now, but feel free to re-open and/or respond if you have further issues. And thanks for giving it a whirl!
