### ISSUE TITLE
Invalid Characters for renaming in episode names

### ISSUE THREAD

**Issue by jimblex** [keithfancher/tvmv#4]
"<stdout>: commitAndReleaseBuffer: invalid argument (invalid character)"

I had this issue when I was renaming my files for Shoresy Season 1. I would always get this message on episode 4 whose name in tmbd is "If You Can’t Win, Don’t Play". I know that the ' in "can't" is causing the problem but I am unsure as to why. It totes that this is an invalid argument and I am assuming it isn't playing well with the code as it is probably ending a ' ' sanitization for the title of the episodes and then parsing the "t" as a line of code. 

Maybe add a line of code to remove all ' from the name or some logic to add delimiters?

I am on a Windows machine so this may also be part of the problem.

**Comment by jimblex** [comment]
Preparing to execute the following 6 rename operations...

\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy.S01E01.mp4 ->
\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy - s01e01 - Never Lose Again.mp4

\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy.S01E02.mp4 ->
\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy - s01e02 - Veteran Presence.mp4

\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy.S01E03.mp4 ->
\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy - s01e03 - Know Your Role.mp4

\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy.S01E04.mp4 ->
\\NAS\plexmediafiles\TV Shows\Shoresy\Shoresy - s01e04 - If You Cantvmv.exe: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)

**Comment by keithfancher** [comment]
Thank you for filing this! I think I see what's going on here.

It is indeed a Windows-specific issue, related to Unicode. Unlike many (most?) of the episode metadata I've come across in TMDB, that episode of Shoresy uses "smart" quotes instead of "normal" quotes. (For example: ’ instead of ' in "can't".)

Unfortunately, the Windows command-line default behavior is just to poop out when it encounters Unicode characters. For a workaround that I *think* should get you going again, see [this note](https://github.com/keithfancher/kept#important-note-for-windows-users) in the README of another project of mine. (This is not the first time I've seen this issue, I'm sorry to say.)

That said, I'll think more about how to "fix" this on the `tvmv` side as well. I think an option to use only the [Portable Filename Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282) for filenames would be useful, to make sure that files you rename on one OS will be pretty much guaranteed to work on any other OS. And a side-effect would be not trying to throw Unicode characters at poor ol' Windows :')
